---
- name: Validate OpenSSH configuration
  ansible.builtin.command:
    argv:
      - /usr/sbin/sshd
      - -t
  changed_when: false

- name: Reload OpenSSH
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: restarted
